---
- hosts: all
  pre_tasks:
    # The version string below is the highest of all those in roles' metadata:
    # "min_ansible_version". It needs to be kept manually up-to-date.
    - name: Verify Ansible meets min required version
      assert:
        that: "ansible_version.full is version_compare('2.8', '>=')"
        msg: >
          "You must update Ansible to at least 2.8 to use this version of Pulp 3 Installer."
  roles:
    # Includes running pulp_webserver. letsencrypt depends on a webserver
    # that can host the .well-known directory.
    - pulp_all_services
    - role: lexa-uw.letsencrypt
      become: true
  tasks:
    # Must be run via a task so that it can be run more than once.
    - name: Run pulp_webserver a 2nd time to import the key
      include_role:
        name: pulp_webserver
      vars:
        pulp_webserver_tls_key: "/etc/letsencrypt/private_key.pem"
        pulp_webserver_tls_cert: "/etc/letsencrypt/fullchain.pem"
        pulp_webserver_tls_files_remote: true
  environment:
    DJANGO_SETTINGS_MODULE: pulpcore.app.settings
