---
pulp_webserver_server: nginx
pulp_content_bind: '127.0.0.1:24816'
pulp_api_bind: '127.0.0.1:24817'
pulp_configure_firewall: auto

pulp_webserver_disable_https: false
pulp_webserver_tls_folder: '{{ pulp_config_dir }}'
pulp_webserver_httpd_servername: '{{ ansible_fqdn }}'
# The "static" dir is used by Pulp 2, and has conflicting SELinux policies.
# https://pulp.plan.io/issues/5995
pulp_webserver_static_dir: "{{ pulp_user_home | regex_replace('\\/$', '') }}/pulpcore_static/"
pulp_webserver_tls_files_remote: false
